apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base

configMapGenerator:
- behavior: merge
  literals:
  - ENV=prod
  - KEYCLOAK_ISSUER=http://keycloak.platform.svc:8080/realms/cauri-prod
  - VERIDOC_URL=http://api.veridoc-id.com
  - AWS_ENDPOINT_URL=http://localstack.platform.svc:4566
  - AWS_REGION=us-east-1
  - S3_BUCKET_PREFIX=cauri-prod-
  - SQS_QUEUE_PREFIX=prod-
  - LEDGER_CORE_URL=http://ledger-core.prod.svc:8080
  name: kyc-service-config

images:
- name: ghcr.io/demo-org-np-migration/kyc-service
  newName: ghcr.io/demo-org-np-migration/kyc-service
  newTag: sha-5da0d80
