apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

configMapGenerator:
  - name: kyc-service-config
    envs:
      - config.yaml

images:
  - name: ghcr.io/demo-org-np-migration/kyc-service
    newTag: latest
